# Scan my node app for semantic vulnerabilities with GitHub Code Scanning
# Upload any vulnerabilities back into my GitHub Repo for developer review.

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
# - task: NodeTool@0
#   inputs:
#     versionSpec: '10.x'
#   displayName: 'Install Node.js'

# - script: |
#      npm install
#   displayName: 'npm install and test'
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- script: |
    # wget https://github.com/github/codeql-action/releases/latest/download/codeql-runner-linux
    wget https://github.com/github/codeql-action/releases/download/codeql-bundle-20200826/codeql-runner-linux
    chmod +x codeql-runner-linux
  displayName: 'Get latest CodeQL package. Install on Agent.'

- script: |
    ./codeql-runner-linux init \
    --repository Gopalakrishnan997/time-tracker \
    --github-url https://github.com \
    --github-auth $(GITHUB_PAT) \
    --config-file .github/workflows/codeql.yml 
      - name: Autobuild
      uses: github/codeql-action/autobuild@v2
  displayName: 'Initialize CodeQL Executable and create a CodeQL database'
- script: |
    ./codeql-runner-linux autobuild --language=java

  
- script: |
    ./codeql-runner-linux analyze \
    --repository Gopalakrishnan997/time-tracker \
    --github-url https://github.com \
    --github-auth $(GITHUB_PAT) \
    --commit $(Build.SourceVersion) \
    --ref $(Build.SourceBranch)
  displayName: 'Populate the CodeQL runner databases, analyze them, and upload the results to GitHub.'
