name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Authenticate with Azure DevOps
        

        run: |
         echo "<settings>
           <mirrors>
             <mirror>
               <id>azure-mirror</id>
               <url>https://pkgs.dev.azure.com/gkinfrastructureascode/java-springboot-maven/_packaging/test/maven/v1</url>
               <mirrorOf>*</mirrorOf>
             </mirror>
           </mirrors>
           <servers>
             <server>
               <id>test</id>
               <username>gkinfrastructureascode</username>
               <password>a7mzdl4mnzgyqsbmgkxpo6g6q4yq4lbznniva7d44hbj2lbzipda</password>
             </server>
           </servers>
         </settings>" > $HOME/.m2/settings.xml

        env:
          AZURE_DEVOPS_TOKEN: a7mzdl4mnzgyqsbmgkxpo6g6q4yq4lbznniva7d44hbj2lbzipda

      - name: Build with Maven
        run: mvn clean package

      # Add more steps for your deployment process
